connection_url: "esm.mshome.net:3003"
log_level: "debug"

# Also supported variables
# extdb_file_path: The full path plus filename for the extDB config
# logging_path: The full path plus filename for the extension to log to
