ws_url: "ws://esm.mshome.net:3001"

# Also supported variables
# extdb_file_path: The full path plus filename for the extDB config
# logging_path: The full path plus filename for the extension to log to
